CREATE USER 'pedro'@'%' IDENTIFIED BY '123';
GRANT ALL PRIVILEGES ON *.* TO 'pedro'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;
use polideportivo;
select * from tbldeporte;
-- inserción
INSERT INTO tbldeporte
(depID_pk, DEPNOMBRE, DEPCANTIDAD_JUGADORES_EQUIPO, DEPCANTIDAD_JUGADORES_EN_EL_CAMPO, DEPCANTIDAD_DE_TIEMPOSDEP, DEPDURACION_DE_CADA_TIEMPO, DEPDURACION_TOTAL_DEL_PARTIDO)
VALUES
(1, 'Fútbol', 11, 11, 2, 45, 90);
-- Update
UPDATE tbldeporte
SET 
    DEPNOMBRE = 'Fútbol Sala',
    DEPCANTIDAD_JUGADORES_EQUIPO = 5,
    DEPCANTIDAD_JUGADORES_EN_EL_CAMPO = 5,
    DEPCANTIDAD_DE_TIEMPOSDEP = 2,
    DEPDURACION_DE_CADA_TIEMPO = 20,
    DEPDURACION_TOTAL_DEL_PARTIDO = 40
WHERE depID_pk = 1;

